<table align="center" width=100%>
    <tr>
        <td width="20%">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=5px>
                    <b> Book Century Identifier - Data Collection<br>
                    </b>
                </font>
            </div>
        </td>
         <td width="25%">
        </td>
    </tr>
</table>

<a id="contents"> </a>
## Table of Contents:

1. **[Objective of this Code](#obj)**
2. **[Importing Required Libraries](#import)**
3. **[Reading the Book List csv file and building the skeleton of the DataFrame](#bookscsv)**
4. **[Reading the Book txt files and adding the Content to the DataFrame](#bookstxt)**
5. **[Adding the Target Variable to the DataFrame](#target)**
6. **[Splitting the Content into Rows to get more Documents](#splitdocs)**
7. **[Saving the DataFrame to a csv file](#savecsv)**

<a id="obj"> </a>
## 1. Objective of this Code:

[Back to Contents](#contents)

Before we even think about building an NLP Model, we first need to:
1. Source the Data
2. Clean the Data
3. Build the Target Variable

1. Sourcing the Data:
First things first, I headed over to [Goodreads](https://www.goodreads.com/list/tag/by-century) to get a list of the best books ever written, century-wise.

Selected maybe 5-6 books for each century featured in its own list.

I tried to stick to one entry per franchise and one entry per author. This wasn't always possible, as intact text content from the 16th century isn't always readily available.

Then I obtained these books off the internet, mostly [Project Gutenberg](https://www.gutenberg.org/).

I put together a simple table with the columns 'Name', 'Author', and 'Year' on [Google Sheets](https://docs.google.com/spreadsheets/d/15w_N4IGD0Sek75qLf8_tU8KctR3UteKc3lGS8wfQGPk/edit?usp=sharing)

Now it was time to assemble a Dataset, and import the contents of the books to the DataFrame:

<a id="import"> </a>
## 2. Importing Required Libraries:

[Back to Contents](#contents)

In [1]:
# Importing pandas in order to work with DataFrames:
import pandas as pd

# Importing os to navigate file systems and open files to import the book content:
import os

<a id="bookscsv"> </a>
## 3. Reading the Book List csv file and building the skeleton of the DataFrame:

[Back to Contents](#contents)

In [2]:
# reading the csv file to create the dataframe skeleton
books = pd.read_csv('books_list.csv')
books.set_index('Name',inplace=True)
books

                                                       Author  Year
Name
Harry Potter and the Deathly Hallows              J K Rowling  2014
The Hunger Games                              Suzanne Collins  2008
The Kite Runner                               Khaled Hosseini  2003
Life of Pi                                        Yann Martel  2001
The Fault in Our Stars                             John Green  2012
The Help                                     Kathryn Stockett  2009
To Kill a Mockingbird                              Harper Lee  1960
1984                                            George Orwell  1949
The Great Gatsby                           F Scott Fitzgerald  1925
Harry Potter and the Sorcerer's Stone             J K Rowling  1997
The Hobbit                                      J R R Tolkien  1937
Farhenheit 451                                   Ray Bradbury  1953
Pride and Prejudice                               Jane Austen  1813
The Picture of Dorian Gray                        Oscar Wilde  1890
Wuthering Heights                                Emily Bronte  1847
Crime and Punishment                       Fyodor Dostoevsky   1866
Frankenstein                                      Mary Shelly  1818
Through the Looking Glass                       Lewis Carroll  1871
Dracula                                           Bram Stoker  1897
Gulliver's Travels                             Jonathan Swift  1726
Robinson Crusoe                                  Daniel Defoe  1719
The US Constitution                          Founding Fathers  1787
The Decline and Fall of the Roman Empire        Edward Gibbon  1776
The Autobiography of Benjamin Franklin      Benjamin Franklin  1791
The Monk                                        Matthew Lewis  1796
Hamlet                                    William Shakespeare  1601
Macbeth                                   William Shakespeare  1623
Paradise Lost                                     John Milton  1667
The Pilgrim's Progress                            John Bunyan  1678
Leviathan                                       Thomas Hobbes  1651
An Essay Concerning Human Understanding            John Locke  1690
Romeo and Juliet                          William Shakespeare  1597
A Midsummer Night's Dream                 William Shakespeare  1595
Essays                                          Francis Bacon  1597
Edward II                                 Christopher Marlowe  1593
Dr Faustus                                Christopher Marlowe  1588

In [3]:
# Confirming that the index of the dataframe is indeed, the book name:
books.index

Index(['Harry Potter and the Deathly Hallows', 'The Hunger Games',
       'The Kite Runner', 'Life of Pi', 'The Fault in Our Stars', 'The Help',
       'To Kill a Mockingbird', '1984', 'The Great Gatsby',
       'Harry Potter and the Sorcerer's Stone', 'The Hobbit', 'Farhenheit 451',
       'Pride and Prejudice', 'The Picture of Dorian Gray',
       'Wuthering Heights', 'Crime and Punishment', 'Frankenstein',
       'Through the Looking Glass', 'Dracula', 'Gulliver's Travels',
       'Robinson Crusoe', 'The US Constitution',
       'The Decline and Fall of the Roman Empire',
       'The Autobiography of Benjamin Franklin', 'The Monk', 'Hamlet',
       'Macbeth', 'Paradise Lost', 'The Pilgrim's Progress', 'Leviathan',
       'An Essay Concerning Human Understanding', 'Romeo and Juliet',
       'A Midsummer Night's Dream', 'Essays', 'Edward II', 'Dr Faustus'],
      dtype='object', name='Name')

<a id="bookstxt"> </a>
## 4. Reading the Book txt files and adding the Content to the DataFrame:

[Back to Contents](#contents)

The books are in a directory named 'books' which is present in the same directory as the Jupyter Notebook.
I will now add the content from the books to the DataFrame.

In [4]:
directory = r'books'
# Looping through every file in the directory 'books':
for filename in os.listdir(directory):
    # Checking if the file is a txt file (ebook):
    if filename.endswith('.txt'):
        # Opening the file in utf-8 encoding:
        with open(os.path.join(directory, filename), encoding='utf-8') as f:
            # Getting the file name without the extension:
            filename_raw = filename.split(sep='.')[0]
            # Saving the contents of the text file into the variable book:
            book = f.read()
            # 2. Cleaning the Data:
            # Removing the newline characters:
            book_cleaned = book.replace('\n', ' ')
            # Adding the content to the respective record with the book name as the index, in a column named 'Content':
            books.loc[filename_raw, 'Content'] = book_cleaned[5000:55000]

In [5]:
# Checking that the contents of every book were added to the DataFrame:
books

,Author,Year,Content
Name,,,
Harry Potter and the Deathly Hallows,J K Rowling,2014,"ldemort, indicating the seat on his immediate ..."
The Hunger Games,Suzanne Collins,2008,"ven here, even in the middle of nowhere, you w..."
The Kite Runner,Khaled Hosseini,2003,"of yours?"" He'd close the door, leave me to w..."
Life of Pi,Yann Martel,2001,to confess that as a matter of fact it was a ...
The Fault in Our Stars,John Green,2012,"tion of cookies and lemonade, sat down in the ..."
The Help,Kathryn Stockett,2009,up her eyes at me like I done something wrong...
To Kill a Mockingbird,Harper Lee,1960,"ustry, Atticus was related by blood or marriag..."
1984,George Orwell,1949,except a series of bright-lit tableaux occurri...
The Great Gatsby,F Scott Fitzgerald,1925,d. “How do you get to West Egg village?” he a...
Harry Potter and the Sorcerer's Stone,J K Rowling,1997,n't see a single collecting tin. It was on his...
The Hobbit,J R R Tolkien,1937,"es, which are known now to few people. If the ..."
Farhenheit 451,Ray Bradbury,1953,"never wash it off completely.” “No, you don’t..."
Pride and Prejudice,Jane Austen,1813,she had no knowledge of it. It was then disclo...
The Picture of Dorian Gray,Oscar Wilde,1890,"suddenly started up, and closing his eyes, pla..."
Wuthering Heights,Emily Bronte,1847,"ng row after row, on a vast oak dresser, to th..."
Crime and Punishment,Fyodor Dostoevsky,1866,"ourselves, a man of our blood and our bone, bu..."
Frankenstein,Mary Shelly,1818,tranced my soul and lifted it to heaven. I als...
Through the Looking Glass,Lewis Carroll,1871,grand game of romps with the ball of worsted A...
Dracula,Bram Stoker,1897,"l enter here some of my notes, as they may ref..."
Gulliver's Travels,Jonathan Swift,1726,of our composition before my master _Houyhnhnm...
Robinson Crusoe,Daniel Defoe,1719,were shared among the upper and lower part of...
The US Constitution,Founding Fathers,1787,"day to day, and may be authorized to compel th..."
The Decline and Fall of the Roman Empire,Edward Gibbon,1776,crinus.—Part I. The Death Of Severus.—Tyranny...
The Autobiography of Benjamin Franklin,Benjamin Franklin,1791,"hearing a great noise among them, the commi..."
The Monk,Matthew Lewis,1796,curiosity to hear an Orator so celebrated; Som...
Hamlet,William Shakespeare,1601,". How now, Horatio! You tremble and look pale...."
Macbeth,William Shakespeare,1623,"ust their heels, But the Norweyan lord, survey..."
Paradise Lost,John Milton,1667,s. Who first seduced them to that foul revolt?...
The Pilgrim's Progress,John Bunyan,1678,wler seek to catch his game By divers means!...
Leviathan,Thomas Hobbes,1651,"of both unwounded. But yet, me thinks, the en..."
An Essay Concerning Human Understanding,John Locke,1690,newly brought out of the mine. It is trial and...
Romeo and Juliet,William Shakespeare,1597,"naked weapon is out: quarrel, I will back thee..."
A Midsummer Night's Dream,William Shakespeare,1595,"e in this case, If I refuse to wed Demetrius. ..."
Essays,Francis Bacon,1597,"n, poor shrunken things, full of melancholy an..."
Edward II,Christopher Marlowe,1593,"the nobles, From the parliament. I'll stan..."
Dr Faustus,Christopher Marlowe,1588,nd universal body of the law:[16] This[17...

In [6]:
# Checking the size of the each value in the 'Content' columns:
for item in books['Content']:
    print(len(item))

50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
22125
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000

<a id="target"> </a>
## 5. Adding the Target Variable to the DataFrame:

[Back to Contents](#contents)

The target variable I have in mind here is the century in which the book was written/published.
Unfortunately I couldn't simply get this information from Gutenberg, as the Year they have in their
database is simply the year the book was added to their collection.

This is why I had to put together the dataset myself, at least for this prototype project.

I can extract the Century from the 'Year' column I painstakingly put together manually:

In [7]:
# 3. Building the Target Variable:
# Getting the quotient of the 'Year' column when divided by 100, then adding 1 to get the 'Century'.
# Since this will be a categorical column, let us convert it back to an object.
books['Century'] = ((books['Year']//100) + 1)
books['Century'] = books['Century'].astype(str)

In [8]:
books[['Year','Century']]

                                          Year Century
Name
Harry Potter and the Deathly Hallows      2014      21
The Hunger Games                          2008      21
The Kite Runner                           2003      21
Life of Pi                                2001      21
The Fault in Our Stars                    2012      21
The Help                                  2009      21
To Kill a Mockingbird                     1960      20
1984                                      1949      20
The Great Gatsby                          1925      20
Harry Potter and the Sorcerer's Stone     1997      20
The Hobbit                                1937      20
Farhenheit 451                            1953      20
Pride and Prejudice                       1813      19
The Picture of Dorian Gray                1890      19
Wuthering Heights                         1847      19
Crime and Punishment                      1866      19
Frankenstein                              1818      19
Through the Looking Glass                 1871      19
Dracula                                   1897      19
Gulliver's Travels                        1726      18
Robinson Crusoe                           1719      18
The US Constitution                       1787      18
The Decline and Fall of the Roman Empire  1776      18
The Autobiography of Benjamin Franklin    1791      18
The Monk                                  1796      18
Hamlet                                    1601      17
Macbeth                                   1623      17
Paradise Lost                             1667      17
The Pilgrim's Progress                    1678      17
Leviathan                                 1651      17
An Essay Concerning Human Understanding   1690      17
Romeo and Juliet                          1597      16
A Midsummer Night's Dream                 1595      16
Essays                                    1597      16
Edward II                                 1593      16
Dr Faustus                                1588      16

<a id="splitdocs"> </a>
## 6. Splitting the Content into Rows to get more Documents:

[Back to Contents](#contents)

Since we are trying to capture patterns in the sentence structure, vocabulary and grammar in order to predict the century in which the book was written and not necessarily predict information about the book itself, I am okay with splitting the content down in order to get more documents.

The only danger with this is limiting the vocabulary of each record, and of course, overfitting to the patterns we find in the admittedly limited data I've collected.

In [9]:
# First let us reset the index, since we no longer need the Book Name in order to identify the records
# and preserver the Name Data:
books.reset_index(inplace=True)

In [10]:
# Iterate through the records of the DataFrame
for i in books.index:
    # The US Constitution is ~22000 characters long, so we are limited to 10 documents each consisting of 2000 characters/
    # If the US Constitution is dropped from the DataFrame, we can create more documents.
    # Performing List Comprehension in order to split the content into documents consisting of 2000 characters each:
    books.at[i,'Content']=[books.at[i,'Content'][2000*j:2000*(j+1)] for j in range(0,10)]

In [11]:
# Splitting the individual elements of the lists into their own separate records:
books = books.explode('Content',ignore_index=True)
books

,Name,Author,Year,Content,Century
0,Harry Potter and the Deathly Hallows,J K Rowling,2014,"ldemort, indicating the seat on his immediate ...",21
1,Harry Potter and the Deathly Hallows,J K Rowling,2014,aze had wandered upward to the body revolving ...,21
2,Harry Potter and the Deathly Hallows,J K Rowling,2014,"rt. “At any rate, it remains unlikely that the...",21
3,Harry Potter and the Deathly Hallows,J K Rowling,2014,"a small man halfway down the table, who had b...",21
4,Harry Potter and the Deathly Hallows,J K Rowling,2014,hiss on even after the cruel mouth had stoppe...,21
...,...,...,...,...,...
355,Dr Faustus,Christopher Marlowe,1588,"quod tumeraris:[52] per Jehovam, Gehenna...",16
356,Dr Faustus,Christopher Marlowe,1588,om Faustus doth dedicate himself. This wo...,16
357,Dr Faustus,Christopher Marlowe,1588,"And meet me in my study at midnight, And...",16
358,Dr Faustus,Christopher Marlowe,1588,should be full of vermin.[70] WAGNER. S...,16
359,Dr Faustus,Christopher Marlowe,1588,"llow me. CLOWN. But, do you hear? if I s...",16

<a id="savecsv"> </a>
## 7. Saving the DataFrame to a csv file:

[Back to Contents](#contents)

Now that we have converted our raw Data into a usable DataFrame, let us save it into a csv file. We can always rerun this code, if we want to extract more of the content from the books.

This DataFrame will need to undergo a lot more processing before it is ready for model-building purposes.

In [12]:
# Saving the DataFrame to a csv file:
books.to_csv('books_db.csv')